services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=mysecret'
    ports:
      - '5432:5432'
