spring:
  application.name: FromSpringBeansDependenciesToEvents
  modulith.events:
    # Överkurs: Vad händer om man har flera instanser (ex. podar) av applikationen? :)
    republish-outstanding-events-on-restart: true
    jdbc.schema-initialization.enabled: true


  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mysecret
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgres

  docker:
    compose:
      lifecycle-management: start_only

logging:
  level:
    nu.westlin.fromspringbeansdependenciestoevents: DEBUG
    root: WARN

notification.delay: PT10s